-- SpeedMIS v7 Fresh Install Schema
-- Generated: 2026-04-16

SET FOREIGN_KEY_CHECKS = 0;

-- mis_menus
CREATE TABLE IF NOT EXISTS `mis_menus` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `real_pid` varchar(14) DEFAULT NULL,
  `menu_name` varchar(50) DEFAULT NULL,
  `brief_title` varchar(20) DEFAULT NULL,
  `is_menu_hidden` char(1) DEFAULT NULL,
  `new_gidx` int(11) DEFAULT NULL,
  `auth_code` char(2) DEFAULT NULL,
  `gidx` int(11) DEFAULT NULL,
  `wgidx` int(11) DEFAULT NULL,
  `agidx` int(11) DEFAULT NULL,
  `all_list_member` text DEFAULT NULL,
  `w_all_list_member` text DEFAULT NULL,
  `menu_type` char(2) DEFAULT NULL,
  `up_real_pid` varchar(14) DEFAULT NULL,
  `add_url` varchar(500) DEFAULT NULL,
  `auto_gubun` varchar(6) DEFAULT NULL,
  `sort_g2` float DEFAULT NULL,
  `sort_g4` float DEFAULT NULL,
  `sort_g6` float DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `file_last_update` datetime DEFAULT NULL,
  `file_last_updater` varchar(50) DEFAULT NULL,
  `compile_date` datetime DEFAULT NULL,
  `g01` varchar(30) DEFAULT NULL,
  `g02` int(11) DEFAULT NULL,
  `g03` char(1) DEFAULT NULL,
  `read_only_cond` varchar(500) DEFAULT NULL,
  `brief_insert_sql` varchar(4000) DEFAULT NULL,
  `g06` varchar(100) DEFAULT NULL,
  `g07` char(1) DEFAULT NULL,
  `table_name` varchar(50) DEFAULT NULL,
  `base_filter` varchar(4000) DEFAULT NULL,
  `use_condition` varchar(4000) DEFAULT NULL,
  `delete_query` varchar(100) DEFAULT NULL,
  `g12` char(1) DEFAULT NULL,
  `g13` varchar(1000) DEFAULT NULL,
  `g14` char(1) DEFAULT NULL,
  `g17` char(1) DEFAULT NULL,
  `dbalias` varchar(20) DEFAULT NULL,
  `help_update_deny` bit(1) DEFAULT NULL,
  `help_title` varchar(100) DEFAULT NULL,
  `help_contents` mediumtext DEFAULT NULL,
  `add_logic` mediumtext DEFAULT NULL,
  `add_logic_treat` mediumtext DEFAULT NULL,
  `is_use_print` bit(1) DEFAULT NULL,
  `is_use_form` bit(1) DEFAULT NULL,
  `add_logic_print` mediumtext DEFAULT NULL,
  `language_code` varchar(10) DEFAULT NULL,
  `depth` int(11) DEFAULT NULL,
  `mis_join_pid` varchar(50) DEFAULT NULL,
  `mis_join_list` varchar(300) DEFAULT NULL,
  `trans_id` varchar(50) DEFAULT NULL,
  `is_core_program` varchar(1) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `protection` bit(1) DEFAULT NULL,
  `g08b` varchar(50) DEFAULT NULL,
  `excel_data` varchar(50) DEFAULT NULL,
  `excel_data_midx` int(11) DEFAULT NULL,
  `spreadsheets_url` varchar(300) DEFAULT NULL,
  `spreadsheet_id` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`idx`) USING BTREE,
  KEY `idx_real_pid` (`real_pid`),
  KEY `idx_up_real_pid` (`up_real_pid`),
  KEY `idx_auto_gubun` (`auto_gubun`),
  KEY `idx_use_yn` (`use_yn`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

-- mis_menu_fields
CREATE TABLE IF NOT EXISTS `mis_menu_fields` (
  `idx` bigint(20) NOT NULL AUTO_INCREMENT,
  `real_pid` varchar(14) DEFAULT NULL,
  `sort_order` float DEFAULT NULL,
  `db_field` varchar(2000) DEFAULT NULL,
  `db_table` varchar(50) DEFAULT NULL,
  `alias_name` varchar(100) DEFAULT '',
  `real_pid_alias_name` varchar(100) DEFAULT '',
  `col_title` varchar(100) DEFAULT NULL,
  `col_width` int(11) DEFAULT NULL,
  `grid_view_fixed` bit(1) DEFAULT NULL,
  `grid_view_xs` int(11) DEFAULT NULL,
  `grid_enter` bit(1) DEFAULT NULL,
  `grid_view_sm` int(11) DEFAULT NULL,
  `grid_view_md` int(11) DEFAULT NULL,
  `grid_view_lg` int(11) DEFAULT NULL,
  `grid_view_xl` int(11) DEFAULT NULL,
  `grid_view_hight` int(11) DEFAULT NULL,
  `grid_view_class` varchar(100) DEFAULT '',
  `grid_is_visible_mobile` bit(1) DEFAULT NULL,
  `schema_type` varchar(50) DEFAULT NULL,
  `items` varchar(2000) DEFAULT NULL,
  `schema_validation` varchar(500) DEFAULT NULL,
  `grid_align` varchar(50) DEFAULT NULL,
  `grid_orderby` varchar(50) DEFAULT NULL,
  `grid_relation` varchar(50) DEFAULT NULL,
  `max_length` varchar(50) DEFAULT NULL,
  `default_value` varchar(2000) DEFAULT NULL,
  `group_compute` varchar(2000) DEFAULT NULL,
  `grid_ctl_name` varchar(50) DEFAULT NULL,
  `grid_is_handle` varchar(50) DEFAULT NULL,
  `grid_list_edit` varchar(50) DEFAULT NULL,
  `grid_templete` varchar(50) DEFAULT NULL,
  `prime_key` varchar(2000) DEFAULT NULL,
  `grid_alim` varchar(2000) DEFAULT NULL,
  `required` varchar(50) DEFAULT NULL,
  `form_group` varchar(50) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `remark` varchar(2000) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `trans_id` varchar(50) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `check_result` varchar(200) DEFAULT NULL,
  `grid_x` smallint(6) NOT NULL DEFAULT -1,
  `grid_y` smallint(6) NOT NULL DEFAULT -1,
  `grid_w` smallint(6) NOT NULL DEFAULT 6,
  `grid_h` smallint(6) NOT NULL DEFAULT 1,
  `form_layout_responsive` text DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=22638 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_menu_auth
CREATE TABLE IF NOT EXISTS `mis_menu_auth` (
  `idx` bigint(20) NOT NULL AUTO_INCREMENT,
  `real_pid` varchar(14) NOT NULL,
  `authority_level` int(11) NOT NULL,
  `userid` varchar(50) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `idx_real_pid` (`real_pid`),
  KEY `idx_userid` (`userid`),
  KEY `idx_rp_uid` (`real_pid`,`userid`)
) ENGINE=InnoDB AUTO_INCREMENT=5662402 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_users
CREATE TABLE IF NOT EXISTS `mis_users` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(50) NOT NULL,
  `eng_name` varchar(60) DEFAULT NULL,
  `station_idx` int(11) DEFAULT NULL,
  `user_name` varchar(50) DEFAULT NULL,
  `user_alias` varchar(50) DEFAULT NULL,
  `main_sortable` varchar(500) DEFAULT NULL,
  `is_rest` varchar(1) DEFAULT NULL,
  `sex` varchar(1) DEFAULT NULL,
  `position_code` int(11) DEFAULT NULL,
  `usr_phone` varchar(50) DEFAULT NULL,
  `bank_name` varchar(50) DEFAULT NULL,
  `bank_book_num` varchar(50) DEFAULT NULL,
  `bank_insert_man` varchar(50) DEFAULT NULL,
  `last_college` varchar(50) DEFAULT NULL,
  `college_subject` varchar(50) DEFAULT NULL,
  `intra_phone` varchar(50) DEFAULT NULL,
  `zip_code` varchar(7) DEFAULT NULL,
  `usr_address` varchar(300) DEFAULT NULL,
  `last_address` varchar(300) DEFAULT NULL,
  `hand_phone` varchar(50) DEFAULT NULL,
  `telegram_chat_id` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `attach1` varchar(200) DEFAULT NULL,
  `attach1_count` int(11) DEFAULT NULL,
  `attach1_path` varchar(1000) DEFAULT NULL,
  `attach1_list` varchar(1000) DEFAULT NULL,
  `attach1_midx` int(11) DEFAULT NULL,
  `이력서` varchar(200) DEFAULT NULL,
  `이력서_midx` int(11) DEFAULT NULL,
  `경력증명서` varchar(200) DEFAULT NULL,
  `경력증명서_midx` int(11) DEFAULT NULL,
  `통장사본` varchar(200) DEFAULT NULL,
  `통장사본_midx` int(11) DEFAULT NULL,
  `증명사진` varchar(200) DEFAULT NULL,
  `증명사진_midx` int(11) DEFAULT NULL,
  `주민등록등본` varchar(200) DEFAULT NULL,
  `주민등록등본_midx` int(11) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `delchk` char(1) DEFAULT 'N',
  `ibsa_date` char(10) DEFAULT NULL,
  `toisa_date` char(10) DEFAULT NULL,
  `birth_date` char(10) DEFAULT NULL,
  `sun_moon` char(1) DEFAULT NULL,
  `married` varchar(50) DEFAULT NULL,
  `hobby` varchar(200) DEFAULT NULL,
  `talent` varchar(200) DEFAULT NULL,
  `army` varchar(50) DEFAULT NULL,
  `grade` varchar(50) DEFAULT NULL,
  `service` varchar(100) DEFAULT NULL,
  `period` varchar(50) DEFAULT NULL,
  `house` varchar(50) DEFAULT NULL,
  `hurdle` varchar(50) DEFAULT NULL,
  `bohun` varchar(50) DEFAULT NULL,
  `ipaddress` varchar(20) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `sortnum` int(11) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `passwd_change_date` datetime DEFAULT NULL,
  `my_language_code` varchar(10) DEFAULT NULL,
  `소속거래처idx` int(11) DEFAULT NULL,
  `is_hp_sender` varchar(1) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `입력된업체도메인` varchar(50) DEFAULT NULL,
  `입력된업체명` varchar(50) DEFAULT NULL,
  `승인요청일` datetime DEFAULT NULL,
  `google_id` varchar(100) DEFAULT NULL,
  `google_link` varchar(500) DEFAULT NULL,
  `google_locale` varchar(50) DEFAULT NULL,
  `google_name` varchar(50) DEFAULT NULL,
  `google_picture` varchar(500) DEFAULT NULL,
  `google_gender` varchar(50) DEFAULT NULL,
  `google_email` varchar(50) DEFAULT NULL,
  `auth_version` bigint(20) DEFAULT NULL,
  `appmake_noti__y_n` varchar(1) DEFAULT NULL,
  `appmake_login_last_time` datetime DEFAULT NULL,
  `appmake_read_last_time` datetime DEFAULT NULL,
  `menu_refresh` varchar(1) DEFAULT NULL,
  `menu_refresh_app` varchar(1) DEFAULT NULL,
  `receive__y_n` varchar(1) NOT NULL,
  `jikchaek` varchar(1) NOT NULL,
  `all_push__y_n` varchar(1) NOT NULL,
  `is_stop` varchar(1) DEFAULT NULL,
  `theme` varchar(10) NOT NULL DEFAULT 'light',
  `push__y_n` varchar(1) DEFAULT NULL,
  `is_admin` char(1) NOT NULL DEFAULT 'N' COMMENT 'Y=관리자',
  `use_yn` char(1) NOT NULL DEFAULT '1' COMMENT '1=사용',
  PRIMARY KEY (`idx`),
  UNIQUE KEY `UniqueNum` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21066 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_groups
CREATE TABLE IF NOT EXISTS `mis_groups` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `gname` varchar(50) DEFAULT NULL,
  `using_level` char(2) DEFAULT NULL,
  `all_list_member` varchar(3000) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_group_rules
CREATE TABLE IF NOT EXISTS `mis_group_rules` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `group_idx` int(11) DEFAULT NULL,
  `set_new_station` int(11) DEFAULT NULL,
  `where_code1` char(2) DEFAULT NULL,
  `set_position` char(2) DEFAULT NULL,
  `where_code2` char(2) DEFAULT NULL,
  `set_userid` varchar(50) NOT NULL,
  `is_admin_s` char(1) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `remark` varchar(500) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `chk_flag` char(1) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `protection` bit(1) DEFAULT NULL,
  `auth_code` char(2) DEFAULT NULL COMMENT '메뉴 auth_code 매핑',
  PRIMARY KEY (`idx`),
  KEY `idx_group_idx` (`group_idx`)
) ENGINE=InnoDB AUTO_INCREMENT=1486 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_group_members
CREATE TABLE IF NOT EXISTS `mis_group_members` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `group_idx` int(11) DEFAULT NULL,
  `user_id` varchar(50) DEFAULT NULL,
  `is_admin_s` char(1) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `hit` int(11) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`idx`),
  KEY `idx_group_idx` (`group_idx`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1603413 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_stations
CREATE TABLE IF NOT EXISTS `mis_stations` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `station_name` varchar(50) DEFAULT NULL,
  `station_property` varchar(8) DEFAULT NULL,
  `station_real_name` varchar(50) DEFAULT NULL,
  `표준금액` bigint(20) DEFAULT NULL,
  `수입계정` varchar(1) DEFAULT NULL,
  `지출계정` varchar(1) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `upidx` int(11) DEFAULT NULL,
  `auto_gubun` varchar(20) DEFAULT NULL,
  `sort_g2` bigint(20) DEFAULT NULL,
  `sort_g4` bigint(20) DEFAULT NULL,
  `sort_g6` bigint(20) DEFAULT NULL,
  `sort_g8` bigint(20) DEFAULT NULL,
  `sort_g10` bigint(20) DEFAULT NULL,
  `depth` int(11) DEFAULT NULL,
  `전화번호` varchar(50) DEFAULT NULL,
  `팩스` varchar(50) DEFAULT NULL,
  `주소` varchar(200) DEFAULT NULL,
  `세금계산서메일` varchar(50) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `통장사본3` varchar(500) DEFAULT NULL,
  `통장사본2` varchar(500) DEFAULT NULL,
  `통장사본1` varchar(500) DEFAULT NULL,
  `통장사본` varchar(500) DEFAULT NULL,
  `통장사본_midx` int(11) DEFAULT NULL,
  `사업자등록증` varchar(500) DEFAULT NULL,
  `사업자등록증_midx` int(11) DEFAULT NULL,
  `명함` varchar(500) DEFAULT NULL,
  `명함_midx` int(11) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=565 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_activity_logs
CREATE TABLE IF NOT EXISTS `mis_activity_logs` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `log_type` varchar(8) NOT NULL,
  `menu_idx` bigint(20) DEFAULT NULL,
  `query` varchar(4000) DEFAULT NULL,
  `h_t_t_p__r_e_f_e_r_e_r` varchar(1000) DEFAULT NULL,
  `link_date_time` datetime DEFAULT NULL,
  `link_result` char(2) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `ip` varchar(50) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `h_t_t_p__u_s_e_r__a_g_e_n_t` varchar(4000) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=1088 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_comments
CREATE TABLE IF NOT EXISTS `mis_comments` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `table_m` varchar(50) DEFAULT NULL,
  `excel_idxname` varchar(50) DEFAULT NULL,
  `midx` varchar(50) DEFAULT NULL,
  `real_pid` varchar(14) DEFAULT NULL,
  `contents` varchar(4000) DEFAULT NULL,
  `boardattach1` varchar(500) DEFAULT NULL,
  `boardattach1_midx` int(11) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `refidx` int(11) DEFAULT NULL,
  `sel_like` int(11) DEFAULT 0,
  `sel_hate` int(11) DEFAULT 0,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_favorite_menus
CREATE TABLE IF NOT EXISTS `mis_favorite_menus` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `real_pid` varchar(14) DEFAULT NULL,
  `gidx` int(11) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `remark` varchar(200) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `ip` varchar(50) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `is_main` char(1) DEFAULT NULL,
  `is_public` char(1) DEFAULT NULL,
  `is_not_recently` char(1) DEFAULT NULL,
  `is_send_mail` char(1) DEFAULT NULL,
  `add_url` varchar(500) DEFAULT NULL,
  `w2` bit(1) DEFAULT NULL,
  `h2` bit(1) DEFAULT NULL,
  `no_link` bit(1) DEFAULT NULL,
  `use_template` bit(1) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=1005 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_help
CREATE TABLE IF NOT EXISTS `mis_help` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) DEFAULT NULL,
  `heading` varchar(50) DEFAULT NULL,
  `flag` varchar(10) DEFAULT NULL,
  `contents` varchar(4000) DEFAULT NULL,
  `php_code` varchar(4000) DEFAULT NULL,
  `youtube_code` varchar(50) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_read_history
CREATE TABLE IF NOT EXISTS `mis_read_history` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `real_pid` varchar(14) DEFAULT NULL,
  `widx` varchar(50) DEFAULT NULL,
  `userid` varchar(50) NOT NULL,
  `parent_gubun` int(11) DEFAULT NULL,
  `parent_idx` varchar(50) DEFAULT NULL,
  `push_title` varchar(100) DEFAULT NULL,
  `push_body` varchar(2000) DEFAULT NULL,
  `push_url` varchar(200) DEFAULT NULL,
  `push_device_nums` int(11) DEFAULT NULL,
  `자격` varchar(10) DEFAULT NULL,
  `처리결과` varchar(50) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `read_date` datetime DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=5438 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_shares
CREATE TABLE IF NOT EXISTS `mis_shares` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `real_pid` varchar(14) NOT NULL,
  `use_yn` char(1) DEFAULT '1',
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `update_version` varchar(12) DEFAULT NULL,
  `presql` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_common_data
CREATE TABLE IF NOT EXISTS `mis_common_data` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `real_cid` varchar(14) DEFAULT NULL,
  `gcode` varchar(14) DEFAULT NULL,
  `ggcode` varchar(14) NOT NULL,
  `kcode` varchar(16) DEFAULT NULL,
  `kname` varchar(500) DEFAULT NULL,
  `kname2` varchar(500) DEFAULT NULL,
  `doc_item` varchar(4000) DEFAULT NULL,
  `station` varchar(50) DEFAULT NULL,
  `userid` varchar(50) DEFAULT NULL,
  `flag1` varchar(20) DEFAULT NULL,
  `flag2` varchar(20) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `ip` varchar(50) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `trans_id` varchar(50) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `protection` bit(1) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=1176 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_companies
CREATE TABLE IF NOT EXISTS `mis_companies` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `clon__cust_idx` int(11) DEFAULT NULL,
  `user_id` varchar(50) DEFAULT NULL,
  `거래처명` varchar(50) NOT NULL,
  `구분코드` varchar(8) DEFAULT NULL,
  `tax_idx` int(11) DEFAULT NULL,
  `company_c_e_o` varchar(50) DEFAULT NULL,
  `business_no` varchar(50) DEFAULT NULL,
  `corporation_no` varchar(50) DEFAULT NULL,
  `business_condition` varchar(50) DEFAULT NULL,
  `business_item` varchar(50) DEFAULT NULL,
  `bank_info1` varchar(100) DEFAULT NULL,
  `bank_info2` varchar(100) DEFAULT NULL,
  `bank_info3` varchar(100) DEFAULT NULL,
  `bank_info_brief` varchar(100) DEFAULT NULL,
  `url` varchar(100) DEFAULT NULL,
  `우편번호` varchar(7) DEFAULT NULL,
  `우편주소` varchar(500) DEFAULT NULL,
  `상세주소` varchar(500) DEFAULT NULL,
  `전화번호` varchar(50) DEFAULT NULL,
  `팩스번호` varchar(50) DEFAULT NULL,
  `자재담당_h_p` varchar(50) DEFAULT NULL,
  `취급품목` varchar(500) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_updater` varchar(50) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `is_main_company` varchar(1) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_login_locks
CREATE TABLE IF NOT EXISTS `mis_login_locks` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(50) NOT NULL,
  `fail_count` int(11) DEFAULT 0,
  `last_fail_at` datetime DEFAULT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `idx_uid` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- mis_refresh_tokens
CREATE TABLE IF NOT EXISTS `mis_refresh_tokens` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(50) NOT NULL,
  `token_hash` varchar(64) NOT NULL,
  `expires_at` datetime NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `idx_uid` (`user_id`),
  KEY `idx_hash` (`token_hash`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- mis_attach_list
CREATE TABLE IF NOT EXISTS `mis_attach_list` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `midx` int(11) DEFAULT NULL,
  `table_name` varchar(50) DEFAULT NULL,
  `field_name` varchar(50) DEFAULT NULL,
  `idx_name` varchar(50) DEFAULT NULL,
  `idx_num` varchar(50) DEFAULT NULL,
  `attach_url` varchar(1000) DEFAULT NULL,
  `attach_size` bigint(20) DEFAULT NULL,
  `attach_mime` varchar(50) DEFAULT NULL,
  `download` int(11) DEFAULT NULL,
  `hit` int(11) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `use_yn` char(1) DEFAULT '1',
  `wdate` datetime DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  `last_update` datetime DEFAULT NULL,
  `last_updater` varchar(50) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `field_value_check` varchar(50) DEFAULT NULL,
  `attach_name` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`idx`),
  KEY `idx` (`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=42594 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mis_urls
CREATE TABLE IF NOT EXISTS `mis_urls` (
  `idx` int(11) NOT NULL AUTO_INCREMENT,
  `long_url` varchar(1000) NOT NULL,
  `short_code` varchar(10) NOT NULL,
  `wdate` datetime NOT NULL DEFAULT current_timestamp(),
  `wdater` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE KEY `short_code` (`short_code`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
